### ISSUE TITLE
I don't think react-native-email is working anymore!

### ISSUE THREAD

**Issue by XavierMod** [tiaanduplessis/react-native-email#22] opened 2021-06-16 11:58 UTC
<img width="289" alt="Screenshot 2021-06-16 at 12 57 47" src="https://user-images.githubusercontent.com/50713842/122214833-74879b00-cea2-11eb-8a65-1621899de19c.png">

**Comment by tiaanduplessis** [comment] 2022-05-27 00:19
Duplicate of https://github.com/tiaanduplessis/react-native-email/issues/9

**Closed as completed by tiaanduplessis** 2022-05-27 00:19 UTC
